apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.service.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: forum-service
  name: forum-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: forum-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.service.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: forum-service
    spec:
      containers:
        - env:
            - name: GIN_MODE
              value: release
          image: forum-service
          name: forum-service
          ports:
            - containerPort: 8082
              protocol: TCP
          tty: true
      restartPolicy: Always
