apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.service.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "50051"
      port: 50051
      targetPort: 50051
  selector:
    io.kompose.service: user-service
