# build context should be set to the project root directory

FROM docker.io/library/node:22-alpine AS build

WORKDIR /build
COPY ./frontend .
RUN --mount=type=cache,target=/build/.npm-cache  \
    npm install && \
    npm run build --production
RUN cp -r /build/dist /dist

FROM docker.io/library/nginx:alpine as nginx
COPY --from=build /build/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

FROM docker.io/joseluisq/static-web-server:2.40-alpine AS lite
COPY --from=build /build/dist /public
EXPOSE 80
CMD ["static-web-server", "--port", "80", "--root", "/public"]