import type { Post } from '@/types/forum'
import type { UserRole, PostStatus } from '@/types/common'

const defaultAvatar = 'http://localhost:5173/src/assets/images/default-avatar.png'

// 模拟帖子数据（用于开发测试）
export const mockPosts: Post[] = [
    {
        post_id: '1',
        title: 'Vue3 组件化最佳实践',
        content: '在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...',
        tags: ['vue', 'frontend', 'best-practice'],
        image_urls: [],
        author: { user_id: '101', username: 'Meixin', avatar_url: defaultAvatar, role: 1 as UserRole },
        status: 2 as PostStatus, // 已解决
        views: 320,
        likes: 45,
        stars: 10,
        replies: 12,
        last_reply_at: '2025-11-02T12:00:00Z',
        created_at: '2025-11-01T10:00:00Z',
        updated_at: '2025-11-02T12:00:00Z',
        is_liked: true,
        is_starred: false,
    },
    {
        post_id: '2',
        title: 'TypeScript 类型体操入门',
        content: '本文介绍如何利用 TypeScript 泛型和条件类型实现类型安全的工具函数...',
        tags: ['typescript', 'generics', 'type-system'],
        image_urls: [],
        author: { user_id: '102', username: 'Alice', avatar_url: defaultAvatar, role: 1 as UserRole },
        status: 2 as PostStatus, // 已解决
        views: 210,
        likes: 30,
        stars: 5,
        replies: 8,
        last_reply_at: '2025-11-06T09:20:00Z',
        created_at: '2025-11-05T14:30:00Z',
        updated_at: '2025-11-06T09:20:00Z',
        is_liked: false,
        is_starred: true,
    },
    {
        post_id: '3',
        title: '前端性能优化的 10 个技巧',
        content: '从资源压缩到虚拟列表，这里总结了前端性能优化的常见手段...',
        tags: ['performance', 'optimization', 'frontend'],
        image_urls: [],
        author: { user_id: '103', username: 'Bob', avatar_url: defaultAvatar, role: 1 as UserRole },
        status: 2 as PostStatus, // 已解决
        views: 800,
        likes: 100,
        stars: 20,
        replies: 20,
        last_reply_at: '2025-11-07T09:00:00Z',
        created_at: '2025-11-07T08:15:00Z',
        updated_at: '2025-11-07T09:00:00Z',
        is_liked: true,
        is_starred: true,
    },
    {
        post_id: '4',
        title: '如何设计通用的搜索组件',
        content: '在项目中经常需要搜索功能，本文探讨如何用 TailwindCSS + Vue3 设计一个可复用的搜索组件...',
        tags: ['component', 'tailwindcss', 'vue'],
        image_urls: [],
        author: { user_id: '104', username: 'Charlie', avatar_url: defaultAvatar, role: 1 as UserRole },
        status: 1 as PostStatus, // 未解决
        views: 90,
        likes: 12,
        stars: 3,
        replies: 3,
        last_reply_at: null,
        created_at: '2025-11-10T11:00:00Z',
        updated_at: '2025-11-10T11:00:00Z',
        is_liked: false,
        is_starred: false,
    },
    {
        post_id: '5',
        title: '匿名提问：如何学习 Web Components？',
        content: '我想深入学习 Web Components，但不知道从哪里开始，有没有推荐的学习路径？',
        tags: ['web-components', 'question'],
        image_urls: [],
        author: { user_id: '0', username: '匿名用户', avatar_url: defaultAvatar, role: 1 as UserRole },
        status: 1 as PostStatus, // 未解决
        views: 150,
        likes: 18,
        stars: 2,
        replies: 5,
        last_reply_at: '2025-11-12T18:00:00Z',
        created_at: '2025-11-12T16:45:00Z',
        updated_at: '2025-11-12T16:45:00Z',
        is_liked: false,
        is_starred: false,
    },
]
