import type { Post } from '@/types/forum'

const defaultAvatar = 'http://localhost:5173/src/assets/images/default-avatar.png'

export const mockPosts: Post[] = [
    {
        id: 1,
        title: 'Vue3 组件化最佳实践',
        content:
            '在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...在 Vue3 中，组合式 API 提供了更灵活的组件逻辑组织方式...',
        tags: ['vue', 'frontend', 'best-practice'],
        category: '技术分享',
        author: { id: 101, username: 'Meixin', avatar: defaultAvatar, role: 'student' },
        status: 'approved',
        isAnonymous: false,
        replyCount: 12,
        likeCount: 45,
        viewCount: 320,
        hasCertifiedAnswer: true,
        isLiked: true,
        isBookmarked: false,
        createdAt: '2025-11-01T10:00:00Z',
        updatedAt: '2025-11-02T12:00:00Z',
    },
    {
        id: 2,
        title: 'TypeScript 类型体操入门',
        content: '本文介绍如何利用 TypeScript 泛型和条件类型实现类型安全的工具函数...',
        tags: ['typescript', 'generics', 'type-system'],
        category: '学习笔记',
        author: { id: 102, username: 'Alice', avatar: defaultAvatar, role: 'student' },
        status: 'approved',
        isAnonymous: false,
        replyCount: 8,
        likeCount: 30,
        viewCount: 210,
        hasCertifiedAnswer: false,
        isLiked: false,
        isBookmarked: true,
        createdAt: '2025-11-05T14:30:00Z',
        updatedAt: '2025-11-06T09:20:00Z',
    },
    {
        id: 3,
        title: '前端性能优化的 10 个技巧',
        content: '从资源压缩到虚拟列表，这里总结了前端性能优化的常见手段...',
        tags: ['performance', 'optimization', 'frontend'],
        category: '经验分享',
        author: { id: 103, username: 'Bob', avatar: defaultAvatar, role: 'student' },
        status: 'approved',
        isAnonymous: false,
        replyCount: 20,
        likeCount: 100,
        viewCount: 800,
        hasCertifiedAnswer: false,
        isLiked: true,
        isBookmarked: true,
        createdAt: '2025-11-07T08:15:00Z',
        updatedAt: '2025-11-07T09:00:00Z',
    },
    {
        id: 4,
        title: '如何设计通用的搜索组件',
        content: '在项目中经常需要搜索功能，本文探讨如何用 TailwindCSS + Vue3 设计一个可复用的搜索组件...',
        tags: ['component', 'tailwindcss', 'vue'],
        category: '组件设计',
        author: { id: 104, username: 'Charlie', avatar: defaultAvatar, role: 'student' },
        status: 'pending',
        isAnonymous: false,
        replyCount: 3,
        likeCount: 12,
        viewCount: 90,
        hasCertifiedAnswer: false,
        createdAt: '2025-11-10T11:00:00Z',
        updatedAt: '2025-11-10T11:00:00Z',
    },
    {
        id: 5,
        title: '匿名提问：如何学习 Web Components？',
        content: '我想深入学习 Web Components，但不知道从哪里开始，有没有推荐的学习路径？',
        tags: ['web-components', 'question'],
        category: '问答',
        author: { id: 0, username: '匿名用户', avatar: defaultAvatar, role: 'student' },
        status: 'approved',
        isAnonymous: true,
        replyCount: 5,
        likeCount: 18,
        viewCount: 150,
        hasCertifiedAnswer: false,
        createdAt: '2025-11-12T16:45:00Z',
        updatedAt: '2025-11-12T16:45:00Z',
    },
]
