// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.1
// source: api/user/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求与响应结构
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 1代表编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_backend_api_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          int64                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"` // x64平台的int == int64
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_backend_api_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GetUserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// 批量查：传多个 id
type BatchGetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 数组
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserRequest) Reset() {
	*x = BatchGetUserRequest{}
	mi := &file_backend_api_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserRequest) ProtoMessage() {}

func (x *BatchGetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserRequest.ProtoReflect.Descriptor instead.
func (*BatchGetUserRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetUserRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 批量查：返回多个用户结构
type BatchGetUserResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Users         map[int64]*GetUserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserResponse) Reset() {
	*x = BatchGetUserResponse{}
	mi := &file_backend_api_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserResponse) ProtoMessage() {}

func (x *BatchGetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserResponse.ProtoReflect.Descriptor instead.
func (*BatchGetUserResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetUserResponse) GetUsers() map[int64]*GetUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_backend_api_user_user_proto protoreflect.FileDescriptor

const file_backend_api_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1bbackend/api/user/user.proto\x12\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"y\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x03R\x04role\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"0\n" +
	"\x13BatchGetUserRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"\xa4\x01\n" +
	"\x14BatchGetUserResponse\x12;\n" +
	"\x05users\x18\x01 \x03(\v2%.user.BatchGetUserResponse.UsersEntryR\x05users\x1aO\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.user.GetUserResponseR\x05value:\x028\x012\x94\x01\n" +
	"\vUserService\x12:\n" +
	"\vGetUserInfo\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12I\n" +
	"\x10BatchGetUserInfo\x12\x19.user.BatchGetUserRequest\x1a\x1a.user.BatchGetUserResponseB\x1bZ\x19backend/api/user;userpbb\x06proto3"

var (
	file_backend_api_user_user_proto_rawDescOnce sync.Once
	file_backend_api_user_user_proto_rawDescData []byte
)

func file_backend_api_user_user_proto_rawDescGZIP() []byte {
	file_backend_api_user_user_proto_rawDescOnce.Do(func() {
		file_backend_api_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_api_user_user_proto_rawDesc), len(file_backend_api_user_user_proto_rawDesc)))
	})
	return file_backend_api_user_user_proto_rawDescData
}

var file_backend_api_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_backend_api_user_user_proto_goTypes = []any{
	(*GetUserRequest)(nil),       // 0: user.GetUserRequest
	(*GetUserResponse)(nil),      // 1: user.GetUserResponse
	(*BatchGetUserRequest)(nil),  // 2: user.BatchGetUserRequest
	(*BatchGetUserResponse)(nil), // 3: user.BatchGetUserResponse
	nil,                          // 4: user.BatchGetUserResponse.UsersEntry
}
var file_backend_api_user_user_proto_depIdxs = []int32{
	4, // 0: user.BatchGetUserResponse.users:type_name -> user.BatchGetUserResponse.UsersEntry
	1, // 1: user.BatchGetUserResponse.UsersEntry.value:type_name -> user.GetUserResponse
	0, // 2: user.UserService.GetUserInfo:input_type -> user.GetUserRequest
	2, // 3: user.UserService.BatchGetUserInfo:input_type -> user.BatchGetUserRequest
	1, // 4: user.UserService.GetUserInfo:output_type -> user.GetUserResponse
	3, // 5: user.UserService.BatchGetUserInfo:output_type -> user.BatchGetUserResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_backend_api_user_user_proto_init() }
func file_backend_api_user_user_proto_init() {
	if File_backend_api_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_api_user_user_proto_rawDesc), len(file_backend_api_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_api_user_user_proto_goTypes,
		DependencyIndexes: file_backend_api_user_user_proto_depIdxs,
		MessageInfos:      file_backend_api_user_user_proto_msgTypes,
	}.Build()
	File_backend_api_user_user_proto = out.File
	file_backend_api_user_user_proto_goTypes = nil
	file_backend_api_user_user_proto_depIdxs = nil
}
