syntax = "proto3";

package user;

option go_package = "backend/api/user;userpb";

// 请求与响应结构
message GetUserRequest {
  // 用户 ID
  int64 user_id = 1;
}

message GetUserResponse {
  int64  user_id    = 1;
  string username   = 2;
  int64  role       = 3; // x64 平台的 int == int64
  string avatar_url = 4;
}

// 批量查：传多个 id
message BatchGetUserRequest {
  repeated int64 user_ids = 1;
}

// 批量查：返回多个用户结构
message BatchGetUserResponse {
  map<int64, GetUserResponse> users = 1;
}

service UserService {
  rpc GetUserInfo (GetUserRequest) returns (GetUserResponse);
  rpc BatchGetUserInfo (BatchGetUserRequest) returns (BatchGetUserResponse);
}

